#!/usr/bin/env bash
# owner mirobins@amd.com
# this program is used to set jobs in device42.
# it is a work in progress.
# version 0.10

#source for credentials
PATH=/tool/pandora64/bin:/tool/pandora64/.package/curl-8.8.0/bin:$PATH
CONFIGFILE='./device42_credentials';
jobids=();
jobnames=();
tokenid='';
token='';
userdatafile='';
d42datafile='';

datacenter='NOTSET';
auth_with_d42='NOTSET';
list_snmpjobs='NOTSET';
create_snmpjob='NOTSET';
delete_all_jobs='NOTSET';
delete_job='NOTSET';
run_job='NOTSET';
generate_lists='NOTSET';
format_datafile='NOTSET';
close_session='NOTSET';
echo_token='NOTSET';
skip_logout='NOTSET';


#setting non-default shell options
set -o pipefail;    #if any job in a pipe fails, it all fails.
shopt -s extglob;   #to turn off shopt -u extglob

##source the authentication credentials file.
if [[ -f "$CONFIGFILE" ]]; then
  source "${CONFIGFILE}";
else
  echo "${CONFIGFILE} not found! exiting.";
  exit 1;
fi


#authenticate with server
do_authenticate_with_api () {
  read -r -d, token tokenid <<< $(curl -s --insecure --request POST --user "${user}:${pass}" --location "https://${host}/tauth/1.0/token/" | jq -r .token,.token_id )
}

#extend the token time
do_extend_token_time () {
    read -r -d, token tokenid <<< $(curl -s --insecure --request PUT --Header "Authorization: Bearer ${token}" --Header "Content-Type: application/json" --location "https://${host}/tauth/1.0/token/${tokenid}/" | jq -r .token,.token_id )
}

#get the client keys
do_get_client_keys () {
    curl -s --insecure --request GET --Header "Authorization: Bearer ${token}" --Header "Content-Type: application/json" --location "https://${host}/api/2.0/api_client_keys/" | jq .
}

#funcion to close the session
do_close_session () {
  curl -s --insecure --request DELETE --header "Authorization: Bearer ${token}" --header "Content-Type: application/json" --location  "https://${host}/tauth/1.0/token/${tokenid}" | jq .
}

#get the snmp discovery jobs ids
do_get_snmp_jobs () {
  while read -r ; do
    jobids+=("${REPLY}")
  done < <(curl -s --insecure --request GET --header "Authorization: Bearer ${token}" --header "Content-Type: application/json" --location  "https://${host}/api/1.0/auto_discovery/snmp_disc/" | jq .jobs[].job_id )
}

#get the name of the job from the jobid
do_get_snmp_jobname_from_id () {
  while read -r ; do
    jobnames+=("${REPLY}")
  done < <(curl -s --insecure --request GET --header "Authorization: Bearer ${token}" --header "Content-Type: application/json" --location  "https://${host}/api/1.0/auto_discovery/snmp_disc/" | jq .jobs[].name )
}

#create a snmp job for 1 host
do_list_snmpjobs () {
  echo "list of jobs"
  for i in "${!jobids[@]}"; do
    printf "%s\n" "jobid: ${jobids[i]}      jobname: ${jobnames[i]}";
  done
}

#deletes all the jobs
do_delete_all_snmpjobs () {
  echo
  for i in "${!jobids[@]}"; do
    echo "deleting job id ${jobids[i]} ${jobnames[i]}"
    curl -s --insecure --request DELETE --header "Authorization: Bearer ${token}" --header "Content-Type: application/json" --location  "https://${host}/api/1.0/auto_discovery/snmp_disc/${jobids[i]}/" | jq .
  done
}

#deletes a single job
do_delete_one_snmpjob () {
  echo "function do_delete_one_snmpjob'";
  local jobid="${1}";
  curl -s --insecure --request DELETE --header "Authorization: Bearer ${token}" --header "Content-Type: application/json" --location  "https://${host}/api/1.0/auto_discovery/snmp_disc/${jobid}/" | jq .
}

#convert datafile form user into format device42 understands
do_generate_datafile_from_userfile () {
  local line='';
  local host='';
  local inputfile="$1";
  local outputfile="${inputfile%.*}.d42";
  local dc="${datacenter}";
  local serverline='';

  if [[ ${outputfile} == ".d42" ]]; then
    outputfile="${inputfile}.d42";
  fi
  while read -r line ; do
    if [[ "$line" == '"name":'* ]] ; then
      read line <<< $( echo "${line}" |tr ' ' '+') ;
    fi

    if ! [[ "$line" == '"server":'* ]]; then
      echo "$line";
    fi
  done < "${inputfile}" | grep -v -e 'null' -v -e '"",' | tr -s ': ' '=' | tr -d '"' | tr -s ',\n' '&' > "${outputfile}"

  if [[ $dc != 'NOTSET' ]]; then
    while read -r host ; do
      array+=("$host".amd.com);
    done < ./hostlist/"${dc}".host-sps
  else
    echo "creating empty template without hosts."
  fi

  read serverline <<< $(printf "%s," "${array[@]}";)
  echo "adding serverline to file ${outputfile}";
  echo "server=${serverline%?}" >> "${outputfile}";
}

#creates a job in device42
do_create_snmpjob () {
  local inputfile="${1}";
  echo "function do_create_snmpjob"
  curl -s -k -X POST --show-error --header "Authorization: Bearer ${token}" --location "https://${host}/api/1.0/auto_discovery/snmp_disc/" --data @${inputfile} | jq .
}

# runs a job
do_run_snmpjob () {
  local jobid="$1";
  echo "function do_run_snmpjob";
  curl -s --insecure --request PUT --header 'Accept: application/json' --header "Authorization: Bearer ${token}" --location  "https://${host}/api/1.0/auto_discovery/snmp_disc/" --data "job_id=${jobid}" --data "run=yes" | jq .
}

#function to produce the datafiles from lsf. written by dan
do_generate_lists_from_lsf () {
  local outdir='./hostlist'

  if ! [[ -d ${outdir} ]] ; then
    echo "creating directory hostlists";
    mkdir "${outdir}";
  else
    echo "directory exists. continuing.";
  fi

  echo "generating hostlist files. this will take a moment."
  for i in atl caco dfdc pldc sadc syco; do
    lshosts -w -R "${i}&&emulation" | grep -v HOST|cut -f1 -d' ' > ${outdir}/${i}.1
    bhosts -w -R "${i}&&!lsfmaster" | grep -v HOST|cut -f1 -d' ' > ${outdir}/${i}.2
    sort -u ${outdir}/${i}.[12]> ${outdir}/${i}.hosts
    case "${outdir}/${i}" in
      caco)
        sed 's/$/-ipmi/' ${outdir}/${i}.hosts > ${outdir}/${i}.host-sps
        ;;
      dfdc)
        sed 's/^/mp/' ${outdir}/${i}.hosts > ${outdir}/${i}.host-sps
        ;;
      *)
        sed 's/$/-sp/' ${outdir}/${i}.hosts > ${outdir}/${i}.host-sps
        ;;
    esac
      rm -f ${outdir}/${i}.[12]
    done
}



#usage function for help and info
do_usage () {
  echo " -a authenticate with the server. ex: $0 -a";
  echo " -t echo the auth token. used with -a. used for testing";
  echo " -l is used to list all snmp jobs ex; $0 -l ";
  echo " -c creates a job ex: $0 -c d42data.txt";
  echo " -D deletes all snmp jobs ex: $0 -D ";
  echo " -d deletes a single job using job_id ex: d42j -d 51";
  echo " -r runs a job. ex: $0 -r 51";
  echo " -g generate the data files. ex: $0 -g";
  echo " -f generates d42j jobs file from hostlist file. ex: $0 -f inputfile -j syco";
  echo " -j the datacenter to create jobs for. this is used with the -f argument";
  echo " some options can be combined.";
  echo " ex: $0 -f filename -j dc";
  echo " ex: $0 -atl -c d42data.txt";
  echo " ex: $0 -atl";
  echo " ex: $0 -j syco -f datafile.txt -c datafile.d42";

  skip_logout='yes';
}

do_getopts () {
  if [[ $# -ge 1 ]]; then
    while getopts ":atlDhgc:r:d:f:j:" opt; do
      case $opt in
        a) auth_with_d42='yes';
           if [[ $skip_logout == 'NOTSET' ]]; then
            skip_logout='no';
           fi
          ;;
        l) auth_with_d42='yes';
           list_snmpjobs='yes';
           skip_logout='no';
          ;;
        c) auth_with_d42='yes'
           create_snmpjob='yes';
           d42datafile="${OPTARG}";
           skip_logout='no';
          ;;
        D) auth_with_d42='yes';
           delete_job='yes';
           skip_logout='no'
          ;;
        d) auth_with_d42='yes';
           delete_job="${OPTARG}";
           skip_logout='no';
          ;;
        r) auth_with_d42='yes'
           run_job="${OPTARG}";
           skip_logout='no';
          ;;
        g) auth_with_d42='no';
           generate_lists='yes';
           skip_logout='yes'
          ;;
        f) auth_with_d42='no';
           format_datafile='yes';
           userdatafile="${OPTARG}";
           skip_logout='yes';
           echo ;
          ;;
        t) echo_token='yes';
           skip_logout='yes';
          ;;
        j) datacenter="${OPTARG}";
          ;;
        h) do_usage;
          ;;
      esac
    done
  else
    do_usage;
  fi;
}

##### main #####
do_getopts "$@";
shift $((OPTIND - 1 ));


if [[ $auth_with_d42 == 'yes' ]] ; then
  do_authenticate_with_api;
fi

if [[ $echo_token == 'yes' && $auth_with_d42 == 'yes' ]]; then
  echo "${token}";
fi

if [[ $list_snmpjobs == 'yes' ]]; then
  do_get_snmp_jobs;
  do_get_snmp_jobname_from_id;
  do_list_snmpjobs;
fi

if [[ $format_datafile == 'yes' ]]; then
  if ! [[ -f "${userdatafile}" ]]; then
    echo "${userdatafile} not found!"
    exit 1;
  fi
  do_generate_datafile_from_userfile "${userdatafile}" "${datacenter}";

fi

if [[ $create_snmpjob == 'yes' ]]; then
  echo ;
  do_create_snmpjob "${d42datafile}";
fi

if  [[ $delete_job == +([[:digit:]]) ]]; then
  do_delete_one_snmpjob "${delete_job}";
fi

if [[ $delete_job == 'yes' ]]; then
  do_get_snmp_jobs;
  do_delete_all_snmpjobs;
fi

if [[ $run_job != 'NOTSET' ]]; then
  do_run_snmpjob "${run_job}";
fi

if [[ $generate_lists == 'yes' ]]; then
  do_generate_lists_from_lsf;
fi

# always make sure to close the session
if [[ $skip_logout == 'yes' ]]; then
  exit 0;
else
  do_close_session;
fi
