#!/usr/bin/env bash

BMC_HOST=();

for HOST in "${BMC_HOST[@]}"; do
echo "${HOST}"
curl -s --insecure --request POST \
  -u "root:IL0acces$" \
  https://${HOST}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset \
  -H "Content-Type: application/json" \
  --data '{
    "ResetType": "ForceRestart"
  }' | jq .
done

