#!/usr/bin/env bash

set -o pipefail;

do_host_graceful_restart () {

  local user="$1";
  local pass="$2";
  local host="$3";

  curl -s --insecure -u "${user}:${pass}" --max-time 30 --connect-timeout 10 -X POST \
  -H "Content-Type: application/json" \
  --data '{ "ResetType": "GracefulRestart" }' \
  https://${host}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset |\
  jq  '.error["@Message.ExtendedInfo"][0].MessageId'

}

if [[ $# -lt 3 ]]; then
  echo "usage: $0 user pass hostname"
  exit;
else
  do_host_graceful_restart "$@";
fi



