#!/usr/bin/env bash

set -o pipefail;

do_ilo_get_cpu_model () {
  local user="$1";
  local pass="$2"
  local host="$3";
 read count model <<< $( curl -s --insecure -u ${user}:${pass} --connect-timeout 10 --max-time 30\
  --header 'Content-Type: application/json' -X GET \
  "https://${host}/redfish/v1/Systems/1/" |\
  jq -r '.ProcessorSummary | "\(.Count) \(.Model)"')
  if [[ $? -ne 0 ]] ; then
    echo "timeout";
  fi
}

if [[ $# -lt 3 ]]; then
  echo "usage: $0 user pass hostname";
  exit;
else
  do_ilo_get_cpu_model "$@";
fi

printf "%b\n" "${3}\t${count}\t${model}";

