#!/usr/bin/env bash

set -o pipefail;

do_ilo7_get_location () {

  local user="$1";
  local pass="$2";
  local host="$3";

  curl -s --insecure -u "${user}:${pass}" --max-time 30 --connect-timeout 10 -X GET \
  -H "Content-Type: application/json" \
  https://${host}/redfish/v1/Chassis/1 |\
  jq .Location

}

if [[ $# -lt 3 ]]; then
  echo "usage: $0 user pass hostname-sp datacenter"
  exit;
else
  do_ilo7_get_location "$@";
fi

