#!/usr/bin/env bash

set -o pipefail;

do_ilo7_set_asset () {

  local user="$1";
  local pass="$2";
  local host="$3";
  local data="$4";
  

curl -s --insecure -u "${user}:${pass}" --max-time 30 --connect-timeout 10 -X PATCH \
  -H "Content-Type: application/json" \
  -d "{\"AssetTag\":\"${data}\"}" \
  https://${host}/redfish/v1/Systems/1 |\
  jq  '.error["@Message.ExtendedInfo"][0].MessageId'

}

if [[ $# -lt 4 ]]; then
  echo "usage: $0 user pass hostname-sp datacenter"
  exit;
else
  do_ilo7_set_asset "$@";
fi

