#!/usr/bin/env bash

set -o pipefail;

do_ilo_reset () {

  local user="$1";
  local pass="$2";
  local host="$3";

  curl -s --insecure -u "${user}:${pass}" --max-time 30 --connect-timeout 10 -X POST \
  -H "Content-Type: application/json" \
  --data '{ "ResetType": "ForceRestart" }' \
  https://${host}/redfish/v1/Managers/1/Actions/Manager.Reset |\
  jq  '.error["@Message.ExtendedInfo"][0].MessageId'

}

if [[ $# -lt 3 ]]; then
  echo "usage: $0 user pass hostname"
  exit;
else 
  do_ilo_reset "$@";
fi


