#!/usr/bin/env bash

set -o pipefail;

do_redhat_get_version () {

  local hostlist="$1";

  if [[ -f ${hostlist} ]]; then
    while read -r line ; do 
      printf "%s " "${line%-sp}" ;
      ssh -n -o ConnectTimeout=10 -o BatchMode=yes "mirobins@${line%-sp}" "cat /etc/redhat-release";
    done < ${hostlist} 
  else 
    while read -r line; do
      printf "%s " "${line%-sp}" ;
      ssh -n -o ConnectTimeout=10 -o BatchMode=yes "mirobins@${line%-sp}" "cat /etc/redhat-release";
    done < <(echo "${hostlist}");
  fi
}

if [[ $# -lt 1 ]]; then
  echo "usage: $0 hostname-file"
  exit;
else
  do_redhat_get_version "$@";
fi
