#!/usr/bin/env bash

user="$1";
pass="$2";
host="$3";

if [[ $# -lt 3 ]] ; then
  echo "usage $0 user pass hostname";
  exit 0;
fi

curl -s --insecure -u "${user}:${pass}" -X PATCH -H "Content-Type: application/json" https://${host}/redfish/v1/Managers/1/EthernetInterfaces/1 \
  --data '{
    "DHCPv4": {
      "DHCPEnabled": true,
      "UseDNSServers": true,
      "UseDomainName": true,
      "UseGateway": true,
      "UseNTPServers": false,
      "UseStaticRoutes": true
    }
  }' |  jq '.error["@Message.ExtendedInfo"][0].MessageId'

curl -s --insecure  -u "${user}:${pass}"  -X PATCH  -H "Content-Type: application/json"   https://${host}/redfish/v1/Managers/1/EthernetInterfaces/1 \
  --data '{
    "DHCPv6": {
      "OperatingMode": "Disabled"
    }
  }' |  jq '.error["@Message.ExtendedInfo"][0].MessageId'

  curl -s --insecure  -u "${user}:${pass}" -X PATCH  -H "Content-Type: application/json" https://${host}/redfish/v1/Managers/1/DateTime \
  --data '{
    "StaticNTPServers": ["atldns02.amd.com"],
    "TimeZone": { "Index": 7},
    "PropagateTimeToHost": true
  }' |  jq '.error["@Message.ExtendedInfo"][0].MessageId'



curl -s --insecure --request POST  -u "${user}:${pass}"  https://${host}/redfish/v1/Managers/1/Actions/Manager.Reset \
  -H "Content-Type: application/json" \
  --data '{
    "ResetType": "ForceRestart"
  }' | jq  '.error["@Message.ExtendedInfo"][0].MessageId'

